name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build & Push the Docker image
      run: |
        docker build -t Tasks/Assignment_2/task3_helloworldapp/Dockerfile/autotestapp .
        echo "${{ secrets.DOCKERPW }}" | docker login -u "saritagund" --password-stdin
        docker tag autotestapp saritagund/autotestapp
        docker push saritagund/autotestapp
      
